app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("accounts/", include("allauth.urls")),
    path("dt-content/", include("dt_content.urls")),
    path("summernote/", include("django_summernote.urls")),
    # path('', include('social_django.urls', namespace='social')),  # enable for social login
]

if settings.STRIPE_ENABLED:
    urlpatterns.append(path("stripe/", include("django_stripe.urls")))

if settings.SIMPLE_SENDGRID_ENABLED:
    urlpatterns.append(path("simple-sendgrid/", include("simple_sendgrid.urls")))

if settings.DT_STRIPE_ENABLED:
    urlpatterns.append(path("dt-stripe/", include("dt_stripe.urls")))


if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend([path("__debug__/", include(debug_toolbar.urls))])

django_stripe/urls.py
from django.urls import path
from django.views.generic import TemplateView

from django_stripe import views
from django_stripe.views import checkout_completed_webhook

app_name = "django_stripe"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path(
        "test_checkout/create",
        views.TestCheckoutCreateView.as_view(),
        name="test_checkout_create",
    ),
    path(
        "test_checkout/payment/<str:id>",
        views.TestCheckoutPaymentView.as_view(),
        name="test_checkout_payment",
    ),
    path(
        "webhooks/checkout-completed",
        views.checkout_completed_webhook,
        name="webhook_checkout_completed",
    ),
    path("checkout-success", views.checkout_success, name="checkout_success"),
]

dt_stripe/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import *

app_name = "dt-stripe"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("customers", CustomerListView.as_view(), name="customer-list"),
    path("customers/create", CustomerCreateView.as_view(), name="customer-create"),
    path(
        "customers/<int:customer_id>",
        CustomerDetailView.as_view(),
        name="customer-detail",
    ),
    path("products", ProductListView.as_view(), name="product-list"),
    path("products/create", ProductCreateView.as_view(), name="product-create"),
    path("plans", PlanListView.as_view(), name="plan-list"),
    path("plans/create", PlanCreateView.as_view(), name="plan-create"),
    path("skus", SKUListView.as_view(), name="sku-list"),
    path("skus/create", SKUCreateView.as_view(), name="sku-create"),
]

simple_sendgrid/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import *

app_name = "simple-sendgrid"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("test", TestView.as_view(), name="test"),
]

base/models.py
from django.db import models

# Create your models here.

dt_stripe/models.py
import logging
import stripe

from django.apps import apps
from django.db import models, transaction
from django.utils.translation import gettext_lazy as _
from stripe.api_resources.abstract.listable_api_resource import ListableAPIResource

from . import settings
from .errors import *
from .managers import *

stripe.api_key = settings.SECRET_KEY


# TODO: fix the test console (optional-ize Stripe)
# TODO: create templatetag for StripeJS thing


def list_all(t: ListableAPIResource):
    """Retrieve all objects of type t from Stripe. Should work for
    Product, Plan. SKU.
    """
    objects = []
    last_id = None
    has_more = True

    while has_more:
        response = t.list(limit=100, starting_after=last_id)
        has_more = response.has_more
        objects.append(response.data)
        last_id = objects[-1].id

    return objects


class Customer(models.Model):
    stripe_id = models.CharField(
        _("id"), max_length=128, help_text="Id of Stripe Customer", db_index=True
    )
    name = models.CharField(_("name"), max_length=128, null=True, blank=True)
    email = models.EmailField(_("email"), max_length=254, null=True, blank=True)
    description = models.TextField(
        _("description"), help_text=_("Description for admins"), null=True, blank=True
    )

    SOURCE_NONE = "NA"
    SOURCE_FAILED = "FA"
    SOURCE_AVAILABLE = "AV"
    source_status_choices = [
        (SOURCE_NONE, "None"),
        (SOURCE_FAILED, "Source payment failed"),
        (SOURCE_AVAILABLE, "Source available"),
    ]
    source_status = models.CharField(
        _("source status"),
        max_length=2,
        choices=source_status_choices,
        default=SOURCE_NONE,
    )

    default_source_id = models.CharField(
        _("default source id"), max_length=128, null=True
    )
    default_source_brand = models.TextField(_("default source brand"), null=True)
    default_source_last4 = models.CharField(
        _("default source last 4 digits"), max_length=4, null=True
    )

    def save(self, *args, **kwargs):
        if self._state.adding:  # initial save
            self._create_stripe_object()
        super().save(*args, **kwargs)

    def _create_stripe_object(self):
        stripe_object = stripe.Customer.create(
            email=self.email, name=self.name, description=self.description
        )
        self.stripe_id = stripe_object.id

    def set_source(self, token, **kwargs):
        try:
            customer = stripe.Customer.modify(self.stripe_id, source=token)
            source = customer.sources.data[0]
        except stripe.error.StripeError as e:
            raise DtStripeError.from_stripe_error(e)
        self.source_status = Customer.SOURCE_AVAILABLE
        self.default_source_id = source.id
        self.default_source_brand = source.brand
        self.default_source_last4 = source.last4
        self.save()

    def order(self, sku, token=None, **kwargs):
        try:
            stripe_order = stripe.Order.create(
                customer=self.stripe_id,
                currency=sku.currency,
                items=[{"type": "sku", "parent": sku.stripe_id}],
            )
            if token:
                stripe_order = stripe.Order.pay(stripe_order.id, source=token)
            else:
                stripe_order = stripe.Order.pay(
                    stripe_order.id, customer=self.stripe_id
                )
        except stripe.error.StripeError as e:
            self.source_status = Customer.SOURCE_FAILED
            self.save()
            raise DtStripeError.from_stripe_error(e)
        order = Order(stripe_id=stripe_order.id, customer=self, sku=sku)
        order.save()
        return order

    def subscribe(self, plan):
        # TODO: prevent duplicate subscriptions
        sub = self.get_subscription(plan)
        status = sub.status
        if status == Subscription.SUBSCRIPTION_ACTIVE:
            raise DtStripeError(
                "DUPLICATE_SUBSCRIPTION", "Attempting a duplicate subscription."
            )
        elif status == Subscription.SUBSCRIPTION_CANCEL_AT_PERIOD_END:
            try:
                stripe_sub = stripe.Subscription.modify(
                    sub.stripe_id, cancel_at_period_end=True
                )
            except stripe.error.StripeError as e:
                raise DtStripeError.from_stripe_error(e)
        else:  # CANCELED or NONE
            try:
                stripe_sub = stripe.Subscription.create(
                    customer=self.stripe_id, plan=plan.stripe_id
                )
            except stripe.error.StripeError as e:
                self.source_status = Customer.SOURCE_FAILED
                self.save()
                raise DtStripeError.from_stripe_error(e)
        sub.stripe_id = stripe_sub.id
        sub.status = Subscription.SUBSCRIPTION_ACTIVE
        sub.save()
        return sub

    def cancel_subscription(self, plan):
        sub = self.get_subscription(plan)
        if not sub or sub.status != Subscription.SUBSCRIPTION_ACTIVE:
            raise DtStripeError(
                "NO_ACTIVE_SUBSCRIPTION", "There is no active subscription to cancel."
            )
        try:
            stripe.Subscription.modify(sub.stripe_id, cancel_at_period_end=True)
        except stripe.error.StripeError as e:
            raise DtStripeError.from_stripe_error(e)
        sub.status = Subscription.SUBSCRIPTION_CANCEL_AT_PERIOD_END
        sub.save()
        return sub

    def get_subscription(self, plan):
        obj, created = self.subscriptions.get_or_create(plan=plan)
        return obj

    def get_subscription_status(self, plan):
        return self.get_subscription(plan).status

    def __str__(self):
        try:
            return self.name
        except AttributeError:
            return "Incomplete customer"


class Product(models.Model):
    stripe_id = models.CharField(
        _("id"), max_length=128, help_text="Id of Stripe Product", db_index=True
    )
    name = models.CharField(_("name"), max_length=128)
    description = models.TextField(
        _("description"),
        help_text=_(
            "Description to be shown to the user. Only for products of type 'good'."
        ),
        null=True,
        blank=True,
    )

    GOOD = "good"
    SERVICE = "service"
    TYPE_CHOICES = [(GOOD, "Good"), (SERVICE, "Service")]
    product_type = models.CharField(_("type"), max_length=16, choices=TYPE_CHOICES)

    SYNC_FIELDS = ["name", "description"]

    objects = models.Manager()
    services = ServiceManager()
    goods = GoodManager()

    def save(self, *args, **kwargs):
        if self._state.adding:  # initial save
            self._create_stripe_object()
        super().save(*args, **kwargs)

    def _create_stripe_object(self):
        if self.product_type == "good":
            stripe_object = stripe.Product.create(
                name=self.name, type=self.product_type, shippable=False
            )
        else:
            stripe_object = stripe.Product.create(
                name=self.name, type=self.product_type
            )
        self.stripe_id = stripe_object.id

    @classmethod
    def sync(cls, product):
        """Update or create internal Product object according to product object
        from stripe API.
        """
        try:
            local_product = Product.get(stripe_id=product.id)
        except Product.DoesNotExist:
            local_product = Product

        local_product.product_type = product.type
        for field in cls.SYNC_FIELDS:
            setattr(local_plan, field, getattr(plan, field))
        local_plan.save()

        return local_plan

    @staticmethod
    def sync_all():
        products = list_all(stripe.Product)
        for product in products:
            Product.sync(product)

    def __str__(self):
        try:
            return self.name
        except AttributeError:
            return "Incomplete product"


class Plan(models.Model):
    stripe_id = models.CharField(
        _("id"), max_length=128, help_text=_("Id of Stripe Plan"), db_index=True
    )

    DAILY = "day"
    WEEKLY = "week"
    MONTHLY = "month"
    YEARLY = "year"
    INTERVAL_CHOICES = [
        (DAILY, "Daily"),
        (WEEKLY, "Weekly"),
        (MONTHLY, "Monthly"),
        (YEARLY, "Yearly"),
    ]

    product = models.ForeignKey(Product, on_delete="CASCADE", related_name="plans")
    amount = models.IntegerField(_("amount"))
    currency = models.CharField(_("currency"), max_length=3, default="usd")
    interval = models.CharField(_("interval"), max_length=16, choices=INTERVAL_CHOICES)
    interval_count = models.IntegerField(
        _("count"),
        default=1,
        help_text=_(
            "Number of intervals per billing cycle. I.e., interval=month and interval_count=3 for 3 months."
        ),
    )

    name = models.CharField(
        _("name"),
        help_text=_("Local name for use by admins"),
        max_length=128,
        null=True,
    )
    description = models.TextField(
        _("description"),
        help_text=_("Local description for use by admins"),
        null=True,
        blank=True,
    )

    SYNC_FIELD = ["amount", "currency", "interval", "interval_count"]

    objects = PlanManager()

    @staticmethod
    def create(product: Product, name: str = None, **kwargs):
        raise NotImplementedError()

    def save(self, *args, **kwargs):
        if self._state.adding:  # initial save
            self._create_stripe_object()
        super().save(*args, **kwargs)

    def _create_stripe_object(self):
        stripe_object = stripe.Plan.create(
            product=self.product.stripe_id,
            amount=self.amount,
            currency=self.currency,
            interval=self.interval,
            interval_count=self.interval_count,
        )
        self.stripe_id = stripe_object.id

    @classmethod
    def sync(cls, plan):
        """Update or create internal Plan object according to plan object
        from stripe API.
        """

dt_stripe/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import *


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ["name", "email", "description"]
        widgets = {"description": forms.Textarea(attrs={"rows": 3})}


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description", "product_type"]
        widgets = {"description": forms.Textarea(attrs={"rows": 3})}

    def clean(self):
        super().clean()

        if self.cleaned_data.get(
            "product_type"
        ) == Product.SERVICE and self.cleaned_data.get("description"):
            raise ValidationError(
                _("You can't set description for services"), "service_description"
            )


class PlanForm(forms.ModelForm):
    product = forms.ModelChoiceField(queryset=Product.services)

    class Meta:
        model = Plan
        fields = [
            "name",
            "description",
            "product",
            "amount",
            "interval",
            "interval_count",
            "currency",
        ]
        widgets = {"description": forms.Textarea(attrs={"rows": 3})}


class SKUForm(forms.ModelForm):
    product = forms.ModelChoiceField(queryset=Product.goods)

    class Meta:
        model = SKU
        fields = ["name", "description", "product", "price", "currency"]
        widgets = {"description": forms.Textarea(attrs={"rows": 3})}


class SubscribeForm(forms.Form):
    plan = forms.ModelChoiceField(
        queryset=None, empty_label="Select a plan", label="Plan"
    )
    token = forms.CharField(
        max_length=128,
        required=False,
        help_text="Stripe.js token used to reset the source on the customer",
    )

    def __init__(self, *args, customer: Customer, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["plan"].queryset = Plan.objects.not_subscribed_by(customer)

    def subscribe(self, customer: Customer):
        if not hasattr(self, "cleaned_data"):
            raise Exception(
                "cleaned_data is undefined. Maybe you forgot to call `is_valid()`?."
            )
        token = self.cleaned_data.get("token", None)
        plan = self.cleaned_data["plan"]
        if token:
            customer.set_source(token)
        customer.subscribe(plan)


class UnsubscribeForm(forms.Form):
    plan = forms.ModelChoiceField(
        queryset=None, empty_label="Select a plan", label="Plan"
    )

    def __init__(self, *args, customer: Customer, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["plan"].queryset = Plan.objects.subscribed_by(customer)

    def unsubscribe(self, customer: Customer):
        if not hasattr(self, "cleaned_data"):
            raise Exception(
                "cleaned_data is undefined. Maybe you forgot to call `is_valid()`?."
            )
        plan = self.cleaned_data["plan"]
        customer.cancel_subscription(plan)


class OrderForm(forms.Form):
    sku = forms.ModelChoiceField(SKU.objects, empty_label="Select an SKU", label="SKU")
    token = forms.CharField(
        max_length=128,
        required=False,
        help_text="Stripe.js token used to reset the source on the customer",
    )
    save_source = forms.BooleanField(
        required=False, label="Use this card for future payments"
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        save_source = self.cleaned_data["save_source"]
        token = self.cleaned_data["token"]

        if save_source and not token:
            raise forms.ValidationError(
                "You must provide card info to save if for later use"
            )

    def order(self, customer: Customer):
        if not hasattr(self, "cleaned_data"):
            raise Exception(
                "cleaned_data is undefined. Maybe you forgot to call `is_valid()`?."
            )
        sku = self.cleaned_data["sku"]
        save_source = self.cleaned_data["save_source"]
        token = self.cleaned_data["token"]

        if save_source:
            customer.set_source(token)
            token = None
        customer.order(sku, token)

base/views.py
from django.shortcuts import render

dt_stripe/templates/dt_stripe/base.html
{% load static %}

<!-- Uses boilerplate from http://html5boilerplate.com -->
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" />

  <link rel="stylesheet" href="{% static 'dt_stripe/css/stripe_elements.css' %}">
  <link rel="stylesheet" href="{% static 'dt_stripe/css/styles.css' %}">

  {% block head %}
  {% endblock head%}

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous">
    </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</head>

<body>
  <!--[if lt IE 7]>
      <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
  <div class="container pt-5">
    <a href="{% url 'dt-stripe:index' %}" class="text-decoration-none">
      <h1>dt-stripe</h1>
    </a>
    <p>A stripe integration for django-template. By Namgyu Ho (its@namgyu.io).</p>
    <hr>
  </div>

  {% block body %}
  {% endblock body %}

  {% block body_script %}
  {% endblock body_script %}
</body>

</html>

dt_stripe/templates/dt_stripe/customer_create.html
{% extends 'dt_stripe/base.html' %}

{% load bootstrap4 %}

{% block head %}
{% endblock head %}

{% block body %}
<div class="container py-4">
  <div class="row">
    <div class="col-12 col-md-11 col-lg-10 col-xl-8">
      <a href="{% url 'dt-stripe:customer-list' %}" class="btn btn-link">
        <i class="fas fa-chevron-left mr-2"></i>Back
      </a>
      <h1>New customer</h1>
      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="text-right">
          <button class="btn btn-primary" type="submit">Create</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock body %}
{% block body_script %}
{% endblock body_script %}

dt_stripe/templates/dt_stripe/customer_detail.html
{% extends 'dt_stripe/base.html' %}

{% load static %}
{% load bootstrap4 %}
{% load dt_stripe %}

{% block head %}
{% endblock head %}

{% block body %}
<div class="container py-4">
  <div class="row">
    <div class="col-12 col-md-11 col-lg-10 col-xl-8 mb-4">
      <a href="{% url 'dt-stripe:customer-list' %}" class="btn btn-link">
        <i class="fas fa-chevron-left mr-2"></i>Back
      </a>
      <h2>Customer: {{ customer.name }}</h2>
      {% if customer.description %}
      <p>{{ customer.description }}</p>
      {% endif %}
      <p>Source status: {{ customer.get_source_status_display }}</p>
    </div>
    <div class="col-12 col-md-6 mb-4">
      <h3>Place order</h3>

      {% if order_success %}
      <div class="alert alert-primary">
        Your order was successful
      </div>
      {% endif %}

      {% if order_error %}
      <div class="alert alert-danger">
        {{ order_error }}
      </div>
      {% endif %}

      <form id="order-form" action="{% url 'dt-stripe:customer-detail' customer.id %}?action=order" method="post">
        {% csrf_token %}
        {% bootstrap_form_errors order_form 'non_fields' %}
        {% bootstrap_field  order_form.sku %}
        <div class="form-row">
          <label for="card-element">
            Credit or debit card
          </label>
          <div id="card-element" class="mb-3 w-100">
          </div>
          <div id="card-errors" role="alert">
          </div>
        </div>
        {% bootstrap_field  order_form.save_source %}
        <button class="btn btn-primary" type="submit">Confirm</button>
      </form>
    </div>

    <div class="col-12 col-md-6 mb-4">
      <h3>Subscribe</h3>

      {% if subscribe_success %}
      <div class="alert alert-primary">
        Your subscription was successful
      </div>
      {% endif %}

      {% if subscribe_error %}
      <div class="alert alert-danger">
        {{ subscribe_error}}
      </div>
      {% endif %}

      <form action="{% url 'dt-stripe:customer-detail' customer.id %}?action=subscribe" method="post">
        {% csrf_token %}
        {% bootstrap_form_errors subscribe_form 'non_fields' %}
        {% bootstrap_field  subscribe_form.plan %}
        <button class="btn btn-primary" type="submit">Confirm</button>
      </form>
    </div>

    <div class="col-12 col-md-6 mb-4">
      <h3>Unsubscribe</h3>

      {% if unsubscribe_success %}
      <div class="alert alert-primary">
        You have been successfully unsubscribed
      </div>
      {% endif %}

      {% if unsubscribe_error %}
      <div class="alert alert-danger">
        {{ unsubscribe_error}}
      </div>
      {% endif %}

      <form action="{% url 'dt-stripe:customer-detail' customer.id %}?action=unsubscribe" method="post">
        {% csrf_token %}
        {% bootstrap_form unsubscribe_form %}
        <button class="btn btn-primary" type="submit">Confirm</button>
      </form>
    </div>
  </div>
</div>
{% endblock body %}

{% block body_script %}
{% dt_stripe_init %}
{% dt_stripe_mount_card_element 'order-form' 'card-element' 'card-errors' %}
{% endblock body_script %}

dt_stripe/templates/dt_stripe/customer_list.html
{% extends 'dt_stripe/base.html' %}

{% block head %}
{% endblock head %}

{% block body %}
<div class="container py-4">
  {% include 'dt_stripe/snippets/commands.html'%}
  {% include 'dt_stripe/snippets/object_list.html'%}
  <div class="row my-5">
    <div class="col-12 col-md-11 col-lg-10 col-xl-8">
      <h3>Customer List</h3>
      {% for customer in customer_list %}
      <div class="card">
        <a href="{% url 'dt-stripe:customer-detail' customer.id %}" class="text-decoration-none">
          <h4>{{ customer.name }}</h4>
          {% if customer.description %}
          <p>{{ customer.description }}</p>
          {% endif %}
        </a>
      </div>
      {% endfor %}
      <div class="text-right">
        <a href="{% url 'dt-stripe:customer-create' %}" class="btn btn-primary">
          Create customer
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock body %}
{% block body_script %}
{% endblock body_script %}

dt_stripe/templates/dt_stripe/plan_create.html
{% extends 'dt_stripe/base.html' %}

{% load bootstrap4 %}

{% block head %}
{% endblock head %}

{% block body %}
<div class="container py-4">
  <div class="row">
    <div class="col-12 col-md-11 col-lg-10 col-xl-8">
      <a href="{% url 'dt-stripe:plan-list' %}" class="btn btn-link">
        <i class="fas fa-chevron-left mr-2"></i>Back
      </a>
      <h1>New plan</h1>
      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="text-right">
          <button class="btn btn-primary" type="submit">Create</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock body %}
{% block body_script %}
{% endblock body_script %}

dt_stripe/templates/dt_stripe/plan_list.html
{% extends 'dt_stripe/base.html' %}

{% block head %}
{% endblock head %}

{% block body %}
<div class="container py-4">
  {% include 'dt_stripe/snippets/commands.html'%}
  {% include 'dt_stripe/snippets/object_list.html'%}
  <div class="row my-5">
    <div class="col-12 col-md-11 col-lg-10 col-xl-8">
      <h3>Plan List</h3>
      {% for plan in plan_list %}
      <div class="card">
        <h4>{{ plan.name }}</h4>
        {% if plan.description %}
        <p>{{ plan.description }}</p>
        {% endif %}
      </div>
      {% endfor %}
      <div class="text-right">
        <a href="{% url 'dt-stripe:plan-create' %}" class="btn btn-primary">
          Create plan
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock body %}
{% block body_script %}
{% endblock body_script %}

dt_stripe/templates/dt_stripe/product_create.html
{% extends 'dt_stripe/base.html' %}

{% load bootstrap4 %}

{% block head %}
{% endblock head %}

{% block body %}
<div class="container py-4">
  <div class="row">
    <div class="col-12 col-md-11 col-lg-10 col-xl-8">
      <a href="{% url 'dt-stripe:product-list' %}" class="btn btn-link">
        <i class="fas fa-chevron-left mr-2"></i>Back
      </a>
      <h1>New product</h1>
      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="text-right">
          <button class="btn btn-primary" type="submit">Create</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock body %}
{% block body_script %}
{% endblock body_script %}

dt_stripe/templates/dt_stripe/product_list.html
{% extends 'dt_stripe/base.html' %}

{% block head %}
{% endblock head %}

{% block body %}
<div class="container py-4">
  {% include 'dt_stripe/snippets/commands.html'%}
  {% include 'dt_stripe/snippets/object_list.html'%}
  <div class="row my-5">
    <div class="col-12 col-md-11 col-lg-10 col-xl-8">
      <h3>Product List</h3>
      {% for product in product_list %}
      <div class="card">
        <h4>{{ product.name }}</h4>
        {% if product.description %}
        <p>{{ product.description }}</p>
        {% endif %}
      </div>
      {% endfor %}
      <div class="text-right">
        <a href="{% url 'dt-stripe:product-create' %}" class="btn btn-primary">
          Create product
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock body %}
{% block body_script %}
{% endblock body_script %}

dt_stripe/templates/dt_stripe/sku_create.html
{% extends 'dt_stripe/base.html' %}

{% load bootstrap4 %}

{% block head %}
{% endblock head %}

{% block body %}
<div class="container py-4">
  <div class="row">
    <div class="col-12 col-md-11 col-lg-10 col-xl-8">
      <a href="{% url 'dt-stripe:sku-list' %}" class="btn btn-link">
        <i class="fas fa-chevron-left mr-2"></i>Back
      </a>
      <h1>New SKU</h1>
      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="text-right">
          <button class="btn btn-primary" type="submit">Create</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock body %}
{% block body_script %}
{% endblock body_script %}