app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("accounts/", include("allauth.urls")),
    path("dt-content/", include("dt_content.urls")),
    path("summernote/", include("django_summernote.urls")),
    # path('', include('social_django.urls', namespace='social')),  # enable for social login
]

if settings.STRIPE_ENABLED:
    urlpatterns.append(path("stripe/", include("django_stripe.urls")))

if settings.SIMPLE_SENDGRID_ENABLED:
    urlpatterns.append(path("simple-sendgrid/", include("simple_sendgrid.urls")))

if settings.DT_STRIPE_ENABLED:
    urlpatterns.append(path("dt-stripe/", include("dt_stripe.urls")))


if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend([path("__debug__/", include(debug_toolbar.urls))])

core/urls.py
from django.urls import path

from .views import *

app_name = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("page/<path:menu_path>/", PageView.as_view(), name="page"),
    path("page/", PageView.as_view(), name="page-base"),
    path("basic/", BasicView.as_view(), name="basic"),
    path("classification/", ClassificationView.as_view(), name="classification"),
    path("api/basic/", BasicAjaxView.as_view(), name="basic-api"),
    path("api/classification/", ClassificationAjaxView.as_view(), name="classification-api"),
]

django_stripe/urls.py
from django.urls import path
from django.views.generic import TemplateView

from django_stripe import views
from django_stripe.views import checkout_completed_webhook

app_name = "django_stripe"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path(
        "test_checkout/create",
        views.TestCheckoutCreateView.as_view(),
        name="test_checkout_create",
    ),
    path(
        "test_checkout/payment/<str:id>",
        views.TestCheckoutPaymentView.as_view(),
        name="test_checkout_payment",
    ),
    path(
        "webhooks/checkout-completed",
        views.checkout_completed_webhook,
        name="webhook_checkout_completed",
    ),
    path("checkout-success", views.checkout_success, name="checkout_success"),
]

dt_content/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views.console import *
from .views.examples import *
from .views.utils import *

app_name = "dt-content"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "toggle-preview-mode",
        TogglePreviewModeView.as_view(),
        name="toggle-preview-mode",
    ),
    path("menus/", MenuListView.as_view(), name="menu-list"),
    path("menus/create/", MenuCreateView.as_view(), name="menu-create"),
    path("menus/update/<slug:slug>/", MenuUpdateView.as_view(), name="menu-update"),
    path("submenus/create/", SubmenuCreateView.as_view(), name="submenu-create"),
    path(
        "submenus/update/<slug:slug>/",
        SubmenuUpdateView.as_view(),
        name="submenu-update",
    ),
    path("menus/delete/<slug:slug>/", MenuDeleteView.as_view(), name="menu-delete"),
    path(
        "content-sections/",
        ContentSectionListView.as_view(),
        name="content-section-list",
    ),
    path(
        "content-sections/update/<slug:slug>/",
        ContentSectionUpdateView.as_view(),
        name="content-section-update",
    ),
    path(
        "content-section/delete/<slug:slug>/",
        ContentSectionDeleteView.as_view(),
        name="content-section-delete",
    ),
    path("content-blocks/", ContentBlockListView.as_view(), name="content-block-list"),
    path(
        "content-block/delete/<slug:slug>/",
        ContentBlockDeleteView.as_view(),
        name="content-block-delete",
    ),
    path("blurbs/", BlurbListView.as_view(), name="blurb-list"),
    path("blurbs/update/<slug:slug>/", BlurbUpdateView.as_view(), name="blurb-update"),
    path("image-blurbs/", ImageBlurbListView.as_view(), name="image-blurb-list"),
    path(
        "image-blurbs/update/<slug:slug>/",
        ImageBlurbUpdateView.as_view(),
        name="image-blurb-update",
    ),
    path(
        "rich-text-blocks/update/<slug:slug>/",
        RichTextBlockUpdateView.as_view(),
        name="rich-text-block-update",
    ),
    path(
        "rich-text-blocks/create/",
        RichTextBlockCreateView.as_view(),
        name="rich-text-block-create",
    ),
    path("example/block/", ExampleStaticBlockView.as_view(), name="example-block"),
    path(
        "example/section/", ExampleStaticSectionView.as_view(), name="example-section"
    ),
    path("example/blurb/", ExampleBlurbView.as_view(), name="example-blurb"),
    path(
        "example/image-blurb/",
        ExampleImageBlurbView.as_view(),
        name="example-image-blurb",
    ),
    path(
        "example/site_test/index/",
        ExampleSiteIndexView.as_view(),
        name="example-site-index",
    ),
    path(
        "example/site_test/<path:menu_path>/",
        ExampleSitePageView.as_view(),
        name="example-site-page",
    ),
    path(
        "example/site_test/",
        ExampleSitePageView.as_view(),
        name="example-site-page-base",
    ),
]

dt_stripe/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import *

app_name = "dt-stripe"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("customers", CustomerListView.as_view(), name="customer-list"),
    path("customers/create", CustomerCreateView.as_view(), name="customer-create"),
    path(
        "customers/<int:customer_id>",
        CustomerDetailView.as_view(),
        name="customer-detail",
    ),
    path("products", ProductListView.as_view(), name="product-list"),
    path("products/create", ProductCreateView.as_view(), name="product-create"),
    path("plans", PlanListView.as_view(), name="plan-list"),
    path("plans/create", PlanCreateView.as_view(), name="plan-create"),
    path("skus", SKUListView.as_view(), name="sku-list"),
    path("skus/create", SKUCreateView.as_view(), name="sku-create"),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dropout, Flatten, Dense

mobilenet = keras.applications.MobileNetV3Small(input_shape=(224, 224, 3), include_top=False, weights='imagenet')

model = keras.models.Sequential()
model.add(mobilenet)
model.add(Flatten())
model.add(Dense(256, activation= 'relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation= 'sigmoid'))

model.compile(
    optimizer=keras.optimizers.Adam(1e-3),
    loss="binary_crossentropy",
    metrics=["accuracy"],
)

model.load_weights("weights.h5")

class BasicForm(forms.Form):
    student_number = forms.IntegerField()


class ClassificationForm(forms.Form):
    image = forms.ImageField()

    def clean_image(self):
        image = self.cleaned_data["image"]
        # save image to image.jpg
        with image.open(mode="rb") as f:
            data = f.read()
        with open("image.jpg", "wb") as f:
            f.write(data)

        img = keras.preprocessing.image.load_img(
            "image.jpg", target_size=(224, 224)
        )
        img_array = keras.preprocessing.image.img_to_array(img)
        img_array = tf.expand_dims(img_array, 0)  # Create batch axis

        predictions = model.predict(img_array)
        score = predictions[0]
        print(
            "This image is %.2f percent cat and %.2f percent dog."
            % (100 * (1 - score), 100 * score)
        )
        self.p = 1 - float(score)

        return image

core/views.py
import json

from django.apps import apps
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import FormView

from core.forms import BasicForm, ClassificationForm
from dt_content.views.core import PageView as BasePageView


class IndexView(BasePageView):
    template_name = "core/index.html"
    menu_base_url = reverse_lazy("core:page-base")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["dt_stripe"] = apps.is_installed("dt_stripe")
        context["simple_sendgrid"] = apps.is_installed("simple_sendgrid")
        return context


class PageView(BasePageView):
    template_name = "core/page.html"
    menu_base_url = reverse_lazy("core:page-base")


db_names = [
    "도윤",
    "서아",
    "서준",
    "하윤",
    "하준",
    "지안",
    "은우",
    "서윤",
    "시우",
    "하은"
    "이준",
    "지호",
]


class BasicView(FormView):
    form_class = BasicForm
    template_name = "core/basic_form.html"

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        number = form.cleaned_data["student_number"]
        name = db_names[number]
        return render(self.request, "core/basic_result.html", context={
            "number": number,
            "name": name
        })


class ClassificationView(FormView):
    form_class = ClassificationForm
    template_name = "core/classification_form.html"

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        return render(self.request, "core/classification_result.html", context={
            "p": form.p,
        })


class BasicAjaxView(FormView):
    form_class = BasicForm

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        number = form.cleaned_data["student_number"]
        name = db_names[number]
        return JsonResponse({
            "number": number,
            "name": name
        })


class ClassificationAjaxView(FormView):
    form_class = ClassificationForm

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        p = form.p
        return JsonResponse({
            "cat_probability": p,
        })

dt_content/views/core.py
import logging
from typing import Tuple

from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.generic.base import ContextMixin, TemplateView

from ..menu import get_nav_menu_list
from ..mixins import PreviewModeMixin
from ..models import *


class PageContextMixin(PreviewModeMixin, ContextMixin):
    """
    Examle usage:

    URL path: /menus/<parent_menu_slug>/<child_menu_slug?>
    URL pattern: /menus/<path:menu_path>
    `menu_base_url`: "/menus"
    `menu_path_kwarg`: "menu_path"

    ## Optimization Notes
    - Need to combine `get_current_menu` and `get_menu_list` for optimal performance.
      These methods are called for **every** page load.
    """

    menu_base_url = "/"
    menu_path_kwarg = "menu_path"

    def get_menu_base_url(self):
        return str(self.menu_base_url)  # may be lazy

    def get_current_menu(self, request):
        menu_path = self.kwargs.get(self.menu_path_kwarg)
        if not menu_path:
            return None

        slugs = menu_path.split("/")

        if len(slugs) not in [1, 2]:
            logging.warning("Invalid menu_path {}".format(menu_path))

        parent_slug = slugs[0]
        parent = get_object_or_404(Menu, url_slug=parent_slug, parent=None)

        if len(slugs) == 2:
            child_slug = slugs[1]
            child = get_object_or_404(Menu, url_slug=child_slug, parent=parent)
            return child

        return parent

    def get_nav_menu_list(self):
        return get_nav_menu_list(
            self.get_menu_base_url(), self.request.path, self.get_preview_mode()
        )

    def get_page_context_data(self, **kwargs):
        page_context = dict()

        current_menu = self.get_current_menu(self.request)
        nav_menu_list = self.get_nav_menu_list()

        nav_menu = None
        if current_menu:
            if current_menu.parent:
                parent_menu = current_menu.parent
                child_menu = current_menu
            else:
                parent_menu = current_menu
                child_menu = None

            # Search parent
            for menu in nav_menu_list:
                if menu["id"] == parent_menu.id:
                    nav_menu = menu
                    break
            else:
                logging.warning("Could not find current parent menu in menu_list")

            # Search child if exists
            if child_menu:
                for menu in nav_menu["children"]:
                    if menu["id"] == child_menu.id:
                        nav_menu = menu
                        break
                else:
                    logging.warning("Could not find current child menu in menu_list")
            page_context["content_section"] = current_menu.get_content_section()
            page_context["nav_menu"] = nav_menu

        page_context["nav_menu_list"] = nav_menu_list
        page_context["dt_content_preview_mode"] = self.get_preview_mode()

        return page_context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_page_context_data())
        return context


PageMixin = PageContextMixin  # deprecated


class PageView(PageContextMixin, TemplateView):
    """
    Examle usage:

    URL path: /menus/<parent_menu_slug>/<child_menu_slug?>
    URL pattern: /menus/<path:menu_path>
    `menu_base_url`: "/menus"
    `menu_path_kwarg`: "menu_path"

    ## Optimization Notes
    - Need to combine `get_current_menu` and `get_menu_list` for optimal performance.
      These methods are called for **every** page load.
    """

core/templates/core/basic_form.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% load admin_link %}
{% load static %}
{% load dt_content %}
{% load image_blurb %}

{% block head %}
<title>Django Template</title>
<link rel="stylesheet" href="{% static 'dt_content/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'core/css/navbar.css' %}">
<link rel="stylesheet" href="{% static 'core/css/header.css' %}">
<link rel="stylesheet" href="{% static 'core/css/footer.css' %}">
{% endblock head%}

{% block body %}

{% include 'core/navbar.html' %}

<div class="header header">
  {% image_blurb 'index/background' placeholder='core/img/background.jpg' as image_blurb %}
  <div class="header-background" style="background-image: url('{{ image_blurb.src }}')">
  </div>
  <div class="header-tint"></div>
  <div class="header-content">
    <div class="container h-100 d-flex flex-column justify-content-center">
      <div class="hero-title">기능 1</div>
    </div>
  </div>
</div>

<div class="container my-3">
  {% include image_blurb.update_link_template_name %}
</div>

<div class="content">
  <div class="container py-5">
    <h1>기능 1. 인적 조희</h1>
    <form method="post">
      {% bootstrap_form form %}
      <button class="btn btn-primary">
        제출하기
      </button>
    </form>
  </div>
</div>

{% include 'core/footer.html' %}

{% endblock body %}
{% block body_script %}
{% endblock body_script %}

core/templates/core/basic_result.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% load admin_link %}
{% load static %}
{% load dt_content %}
{% load image_blurb %}

{% block head %}
<title>Django Template</title>
<link rel="stylesheet" href="{% static 'dt_content/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'core/css/navbar.css' %}">
<link rel="stylesheet" href="{% static 'core/css/header.css' %}">
<link rel="stylesheet" href="{% static 'core/css/footer.css' %}">
{% endblock head%}

{% block body %}

{% include 'core/navbar.html' %}

<div class="header header">
  {% image_blurb 'index/background' placeholder='core/img/background.jpg' as image_blurb %}
  <div class="header-background" style="background-image: url('{{ image_blurb.src }}')">
  </div>
  <div class="header-tint"></div>
  <div class="header-content">
    <div class="container h-100 d-flex flex-column justify-content-center">
      <div class="hero-title">기능 1</div>
    </div>
  </div>
</div>

<div class="container my-3">
  {% include image_blurb.update_link_template_name %}
</div>

<div class="content">
  <div class="container py-5">
    <h1>기능 1. 인적 조희</h1>
    <p>{{ number }}번 학생을 조회하셨습니다.</p>
    <p>학생 이름은 {{ name }}입니다.</p>
  </div>
</div>

{% include 'core/footer.html' %}

{% endblock body %}
{% block body_script %}
{% endblock body_script %}

core/templates/core/classification_form.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% load admin_link %}
{% load static %}
{% load dt_content %}
{% load image_blurb %}

{% block head %}
<title>Django Template</title>
<link rel="stylesheet" href="{% static 'dt_content/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'core/css/navbar.css' %}">
<link rel="stylesheet" href="{% static 'core/css/header.css' %}">
<link rel="stylesheet" href="{% static 'core/css/footer.css' %}">
{% endblock head%}

{% block body %}

{% include 'core/navbar.html' %}

<div class="header header">
  {% image_blurb 'index/background' placeholder='core/img/background.jpg' as image_blurb %}
  <div class="header-background" style="background-image: url('{{ image_blurb.src }}')">
  </div>
  <div class="header-tint"></div>
  <div class="header-content">
    <div class="container h-100 d-flex flex-column justify-content-center">
      <div class="hero-title">기능 2</div>
    </div>
  </div>
</div>

<div class="container my-3">
  {% include image_blurb.update_link_template_name %}
</div>

<div class="content">
  <div class="container py-5">
    <h1>기능 2. 사진 분류</h1>
    <form method="post" enctype="multipart/form-data">
      {% bootstrap_form form %}
      <button class="btn btn-primary">
        제출하기
      </button>
    </form>
  </div>
</div>

{% include 'core/footer.html' %}

{% endblock body %}
{% block body_script %}
{% endblock body_script %}

core/templates/core/classification_result.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% load admin_link %}
{% load static %}
{% load dt_content %}
{% load image_blurb %}

{% block head %}
<title>Django Template</title>
<link rel="stylesheet" href="{% static 'dt_content/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'core/css/navbar.css' %}">
<link rel="stylesheet" href="{% static 'core/css/header.css' %}">
<link rel="stylesheet" href="{% static 'core/css/footer.css' %}">
{% endblock head%}

{% block body %}

{% include 'core/navbar.html' %}

<div class="header header">
  {% image_blurb 'index/background' placeholder='core/img/background.jpg' as image_blurb %}
  <div class="header-background" style="background-image: url('{{ image_blurb.src }}')">
  </div>
  <div class="header-tint"></div>
  <div class="header-content">
    <div class="container h-100 d-flex flex-column justify-content-center">
      <div class="hero-title">기능 2</div>
    </div>
  </div>
</div>

<div class="container my-3">
  {% include image_blurb.update_link_template_name %}
</div>

<div class="content">
  <div class="container py-5">
    <h1>기능 2. 사진 분류</h1>
    <p>해당 사진이 고양이일 확률은 {{ p }}입니다.</p>
  </div>
</div>

{% include 'core/footer.html' %}

{% endblock body %}
{% block body_script %}
{% endblock body_script %}

core/templates/core/index.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% load admin_link %}
{% load static %}
{% load dt_content %}
{% load image_blurb %}

{% block head %}
  <title>Django Template</title>
  <link rel="stylesheet" href="{% static 'dt_content/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/navbar.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/header.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/footer.css' %}">
{% endblock head %}

{% block body %}

  {% include 'core/navbar.html' %}

  <div class="header header">
    {% image_blurb 'index/background' placeholder='core/img/background.jpg' as image_blurb %}
    <div class="header-background" style="background-image: url('{{ image_blurb.src }}')">
    </div>
    <div class="header-tint"></div>
    <div class="header-content">
      <div class="container h-100 d-flex flex-column justify-content-center">
        <div class="hero-title">실전창업교육 API 데모</div>
      </div>
    </div>
  </div>

  <div class="container my-3">
    {% include image_blurb.update_link_template_name %}
  </div>

  <div class="content">
    <div class="container py-5">
      <h1>안녕하세요!</h1>

      <h2>기능 1. 인적 조회</h2>
      <a class="btn btn-primary mb-3" href="{% url 'core:basic' %}">
        시작
        <i class="fas fa-chevron-right ml-2"></i>
      </a>

      <h2>기능 2. 사진 분류</h2>
      <a class="btn btn-primary" href="{% url 'core:classification' %}">
        시작
        <i class="fas fa-chevron-right ml-2"></i>
      </a>
    </div>
  </div>

  {% include 'core/footer.html' %}

{% endblock body %}
{% block body_script %}
{% endblock body_script %}

core/templates/core/navbar.html
{% load static %}

<nav class="fixed-top">
  <div class="navbar-top">
    <div class="container">
      <div class="d-flex justify-content-end">
        {% if request.user.is_authenticated %}
        {% if request.user.is_staff %}
        {% if dt_content_preview_mode %}
        <a class="btn navbar-top-button"
          href="{% url 'dt-content:toggle-preview-mode' %}?mode=false&next={{ request.path }}">
          EXIT PREVIEW MODE
        </a>
        {% else %}
        <a class="btn navbar-top-button"
          href="{% url 'dt-content:toggle-preview-mode' %}?mode=true&next={{ request.path }}">
          ENTER PREVIEW MODE
        </a>
        {% endif %}
        {% endif %}
        <a class="btn navbar-top-button" href="{% url 'account_logout' %}">SIGN OUT</a>
        {% else %}
        <a class="btn navbar-top-button" href="{% url 'account_login' %}">LOG IN</a>
        <a class="btn navbar-top-button" href="{% url 'account_signup' %}">SIGN UP</a>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="navbar-middle navbar navbar-expand-lg navbar-dark">
    <div class="container">
      <a class="navbar-brand nav-title" href="{% url 'core:index' %}">
        데모 사이트
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          {% for menu in nav_menu_list %}
          {% if not menu.disabled %}
          <li class="nav-item">
            <a class="nav-link {% if menu.active %}active{% endif %}" href="{{ menu.href }}">{{ menu.title }}</a>
          </li>
          {% endif %}
          {% endfor %}
          {% if request.user.is_staff %}
          {% if not dt_content_preview_mode %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dt-content:menu-create' %}?next={{ request.path }}">
              <i class="fas fa-cog"></i> Add Menu
            </a>
          </li>
          {% endif %}
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
</nav>

core/templates/core/page.html
{% extends 'base/base.html' %}
{% load static %}
{% load dt_content %}

{% block head %}
<title>Django Template</title>
<link rel="stylesheet" href="{% static 'dt_content/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'core/css/navbar.css' %}">
<link rel="stylesheet" href="{% static 'core/css/header.css' %}">
<link rel="stylesheet" href="{% static 'core/css/footer.css' %}">
{% endblock head%}
{% block body %}

{% include 'core/navbar.html' %}

<!-- HEADER -->
<div class="header">
  <div class="header-background" style="background-image: url('{% static 'core/img/background.jpg' %}')">
  </div>
  <div class="header-tint"></div>
  <div class="header-content">
    <div class="container header-container">
      {% if nav_menu.parent %} {# Child #}
      <div class="header-title d-flex flex-row align-items-center">
        <a href="{{ nav_menu.parent.href }}" class="mr-3">{{ nav_menu.parent.title }}</a>
        <i class="fas fa-chevron-right mr-3"></i>
        <a href="{{ nav_menu.href }}" class="mr-3">{{ nav_menu.title }}</a>
      </div>
      {% else %} {# Parent #}
      <div class="header-title">
        <a href="{{ nav_menu.href }}" class="mr-3">{{ nav_menu.title }}</a>
      </div>
      {% endif %}
    </div>
  </div>
</div>

<!-- SUBMENU LIST -->
{% if nav_menu.children  %}
<div class="py-4 border-bottom">
  <div class="container">
    <!--<h2>{{ nav_menu.title }}</h2>-->
    <h2>Submenus</h2>
    {% for child in nav_menu.children %}
    <a href="{{ child.href }}" class="submenu-link">
      <i class="fas fa-chevron-circle-right"> </i>
      {{ child.title }}
    </a>
    {% endfor %}
  </div>
</div>
{% endif %}

{% if request.user.is_staff %}
{# Show these options even in preview mode #}
<div class="py-4 border-bottom">
  <div class="container">
    <h3>Admin Options</h3>
    {% if not nav_menu.parent %}
    <a href="{% url 'dt-content:submenu-create' %}?parent={{ nav_menu.id }}&next={{ request.path}}"
      class="submenu-link">
      <i class="fas fa-cog"> </i>
      Add Submenu
    </a>
    <a href="{% url 'dt-content:menu-update' nav_menu.id %}" class="submenu-link">
      <i class="fas fa-cog"> </i>
      Manage Menu
    </a>

    {% else %}
    <a href="{% url 'dt-content:submenu-update' nav_menu.id %}" class="submenu-link">
      <i class="fas fa-cog"> </i>
      Manage Submenu
    </a>
    {% endif %}

    {% if dt_content_preview_mode %}
    <a href="{% url 'dt-content:toggle-preview-mode' %}?mode=false&next={{ request.path }}" class="submenu-link">
      <i class="fas fa-eye"> </i>
      Exit Preview Mode
    </a>
    {% else %}
    <a href="{% url 'dt-content:toggle-preview-mode' %}?mode=true&next={{ request.path }}" class="submenu-link">
      <i class="fas fa-eye"> </i>
      View in Preview Mode
    </a>
    {% endif %}
  </div>
</div>
{% endif %}

<!-- CONTENT -->
<div class="content">
  {% include content_section.template_name %}
</div>

{% include 'core/footer.html' %}

{% endblock body %}

{% block body_script %}
{% endblock body_script %}